runtime: python310
# "api_version" field is not allowed in runtime python312.
# api_version: 1
# "Not supprted in python313 and can safely be removed.""
# threadsafe: true
service_account: "open-speech-recording-443021@appspot.gserviceaccount.com"

# [START handlers]
handlers:
- url: /static
  static_dir: static
  secure: always
- url: /.*
  script: main.app
  secure: always
# [END handlers]

#[START env]
env_variables:
    CLOUD_STORAGE_BUCKET: open_speech_recording_bucket
    SESSION_SECRET_KEY: 0aSNtWHPRo2XaDpuOm49YR5mIn95fjDzDIlEwVzEZpg
#[END env]